<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.CompanyName.Attendly</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Debugger>Xamarin</Debugger>
    <AndroidKeyStore>False</AndroidKeyStore>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Debugger>Xamarin</Debugger>
    <AndroidKeyStore>False</AndroidKeyStore>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
    <PackageReference Include="Xamarin.Google.MLKit.BarcodeScanning" />
    <PackageReference Include="Xamarin.GooglePlayServices.Code.Scanner" />	
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Attendly\Attendly.csproj" />
  </ItemGroup>
</Project>
